import Head from 'next/head'
import Image from 'next/image'
import {useState} from "react";
import blank from '../public/blank.png';

export default function Main() {
  const [url, setUrl] = useState('');
  const [songName, setSongName] = useState('');
  const [thumbnailUrl, setThumbnailUrl] = useState(blank.src);

  const loadedThumbnail = thumbnailUrl !== blank.src;

  return (
    <div className='flex flex-col'>
      <Head>
        <title>YouTube Thumbnail Getter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='container mx-auto flex flex-col justify-center items-center pt-4 px-2'>
        <div className='mb-16'>
          <h1 className='text-2xl md:text-5xl text-center font-bold text-red-600'>
            YouTube Thumbnail Getter
          </h1>
        </div>

        <div>
          <div className='mb-2 flex flex-col px-2'>
            <input type='text' value={url} onChange={x => setUrl(x.target.value)} placeholder='YouTube video URL' className='flex-grow border-b border-red-300 text-sm md:text-2xl outline-none' />
          </div>
          <div className='flex justify-center items-center mb-2'>
            <button type='button' className='flex justify-center items-center w-4/12 bg-red-400 rounded text-white text-sm font-bold md:text-xl p-2 md:p-4 hover:bg-red-600'>Get Thumbnail</button>
          </div>
          <div className='border mb-2'>
            <Image src={thumbnailUrl} alt='Thumbnail image' width='640' height='360' />
          </div>
          <div className='flex justify-end'>
            <button disabled={!loadedThumbnail} className={`flex justify-center items-center w-2/12 bg-red-400 rounded text-white text-sm font-bold md:text-xl p-2 md:p-4 hover:bg-red-600${loadedThumbnail ? '' : ' opacity-25 cursor-not-allowed'}`}>Save</button>
          </div>
        </div>
      </main>

      <footer className='fixed bottom-0 w-full border-t h-16 flex justify-end items-center bg-black text-white'>
        <div className='px-4'>
          <span className='text-sm'>Created by <a href='https://twitter.com/sekiya9311' target='_blank' className='border-b-2 border-white'>@sekiya9311</a></span>
        </div>
      </footer>
    </div>
  )
}
